import { round } from "./utils.mjs";

export function buildMarketSummary(dataset, analysis) {
  const parts = [];
  parts.push(`${dataset.symbol} is classified as ${analysis.detectedRegime} with ${analysis.regimeConfidence}% confidence`);
  parts.push(`trend is ${analysis.trendState.toLowerCase()}`);
  parts.push(`volatility is ${analysis.volatilityState.toLowerCase()}`);
  parts.push(`sentiment is ${analysis.sentimentState.toLowerCase()}`);
  parts.push(`liquidity is ${analysis.liquidityState.toLowerCase()}`);
  return `${parts.join(", ")}.`;
}

export function buildJsonOutput(dataset, request, analysis, strategy, backtestResult) {
  return {
    strategySpec: {
      name: strategy.strategyName,
      version: "1.0.0",
      asset: dataset.symbol,
      timeframe: request.timeframe,
      lookbackDays: request.lookbackDays,
      riskLevel: request.riskLevel,
      strategyFocus: request.strategyFocus,
      dataSource: dataset.dataSource,
      regime: {
        name: analysis.detectedRegime,
        confidence: analysis.regimeConfidence,
        trendState: analysis.trendState,
        volatilityState: analysis.volatilityState,
        sentimentState: analysis.sentimentState,
        liquidityState: analysis.liquidityState,
      },
      rules: {
        entry: strategy.entryRules,
        exit: strategy.exitRules,
        risk: strategy.riskRules,
        invalidation: strategy.invalidationRules,
        noTradeConditions: strategy.noTradeConditions,
      },
      positionSizing: strategy.positionSizing,
      backtest: backtestResult.backtest,
      signals: analysis.signals.map((signal) => ({
        name: signal.name,
        score: signal.score,
        status: signal.status,
        reason: signal.reason,
      })),
    },
  };
}

export function buildCmcSkillOutput(dataset, request, analysis, strategy, backtestResult) {
  return {
    skillType: "strategy_generation",
    skillVersion: "1.0.0",
    project: "BestStrat",
    track: "BNB Hack Track 2 Strategy Skill",
    cmcCompatible: true,
    input: {
      symbol: dataset.symbol,
      timeframe: request.timeframe,
      lookbackDays: request.lookbackDays,
      riskLevel: request.riskLevel,
      strategyFocus: request.strategyFocus,
    },
    output: {
      strategyName: strategy.strategyName,
      detectedRegime: analysis.detectedRegime,
      regimeConfidence: analysis.regimeConfidence,
      entryRules: strategy.entryRules,
      exitRules: strategy.exitRules,
      riskRules: strategy.riskRules,
      invalidationRules: strategy.invalidationRules,
      noTradeConditions: strategy.noTradeConditions,
      backtest: backtestResult.backtest,
    },
    signalWeights: {
      trend: 0.25,
      momentum: 0.2,
      volume: 0.15,
      sentiment: 0.15,
      volatility: 0.15,
      liquidity: 0.1,
    },
    disclaimer: "Research strategy specification only. Not financial advice. No trade execution.",
  };
}

export function buildMarkdownReport(dataset, request, analysis, strategy, backtestResult) {
  const rules = (items) => items.map((item) => `- ${item}`).join("\n");
  const signals = analysis.signals.map((signal) => `| ${signal.name} | ${signal.score} | ${signal.status} | ${signal.reason} |`).join("\n");

  return `# BestStrat Report — ${dataset.symbol}/${request.timeframe}

## Strategy
**Name:** ${strategy.strategyName}  
**Detected Regime:** ${analysis.detectedRegime} (${analysis.regimeConfidence}% confidence)  
**Data Source:** ${dataset.dataSource}

${strategy.strategySummary}

## Market State
- Trend: ${analysis.trendState}
- Volatility: ${analysis.volatilityState}
- Sentiment: ${analysis.sentimentState}
- Liquidity: ${analysis.liquidityState}
- Latest price used by engine: ${round(analysis.current.close, 6)}

## Entry Rules
${rules(strategy.entryRules)}

## Exit Rules
${rules(strategy.exitRules)}

## Risk Rules
${rules(strategy.riskRules)}

## Invalidation Rules
${rules(strategy.invalidationRules)}

## No Trade Conditions
${rules(strategy.noTradeConditions)}

## Backtest Results
| Metric | Value |
|--------|-------|
| Total Return | ${backtestResult.backtest.totalReturn} |
| Win Rate | ${backtestResult.backtest.winRate} |
| Max Drawdown | ${backtestResult.backtest.maxDrawdown} |
| Number of Trades | ${backtestResult.backtest.numberOfTrades} |
| Average Trade Return | ${backtestResult.backtest.averageTradeReturn} |
| Best Trade | ${backtestResult.backtest.bestTrade} |
| Worst Trade | ${backtestResult.backtest.worstTrade} |
| Risk Adjusted Score | ${backtestResult.backtest.riskAdjustedScore} |

## Signal Breakdown
| Signal | Score | Status | Reason |
|--------|-------|--------|--------|
${signals}

---
Generated by BestStrat. Research strategy specification only. Not financial advice. No trade execution.`;
}
